---
abstract: 'front-end to Module::CPANTS::Analyse'
author:
  - 'Kenichi Ishigaki <ishigaki@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.88'
  Test::UseAllModules: '0.10'
configure_requires:
  ExtUtils::MakeMaker::CPANfile: '0.06'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-CPANTS-Lint
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Data::Dumper: '0'
  Getopt::Long: '0'
  Module::CPANTS::Analyse: '0.96'
  Pod::Usage: '0'
  perl: '5.008001'
resources:
  repository: https://github.com/charsbar/App-CPANTS-Lint
version: '0.05'
